# Generated by Django 5.0.1 on 2024-02-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userregister'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='UserRegistrar',
        ),
    ]
