# Generated by Django 5.0.1 on 2024-02-08 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_userregister_userregistrar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(blank=True, related_name='societies_joined', to='app.userregistrar')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='UserSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.ManyToManyField(blank=True, related_name='user_societies', to='app.societymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society', to='app.userregistrar')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
