# Generated by Django 5.0.1 on 2024-02-08 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_societymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrar',
            name='phoneNumber',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')]),
        ),
    ]
