# Generated by Django 5.0.1 on 2024-02-08 19:55

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userregistrar_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrar',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
