# Generated by Django 5.0.1 on 2024-02-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userregistrar_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societymodel',
            name='user',
        ),
        migrations.AddField(
            model_name='userregistrar',
            name='societies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='societies_joined', to='app.societymodel'),
        ),
        migrations.DeleteModel(
            name='UserSociety',
        ),
    ]
